name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd project
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          pip install kaggle

      - name: Create data directory
        run: |
          cd project
          mkdir -p data

      - name: Download Dataset 1 (Emissions)
        run: |
          cd project/data
          kaggle datasets download -d abdelrahman16/co2-emissions-usa
          unzip co2-emissions-usa.zip

      - name: Download Dataset 2 (Renewable Energy Consumption)
        run: |
          cd project/data
          kaggle datasets download -d alistairking/renewable-energy-consumption-in-the-u-s
          unzip renewable-energy-consumption-in-the-u-s.zip

      - name: Run tests
        run: |
          cd project
          chmod +x tests.sh
          ./tests.sh
