name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Kaggle API credentials
      - name: Set up Kaggle API credentials
        run: |
          mkdir -p ~/.kaggle
          echo "${{ secrets.KAGGLE_JSON }}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      # Step 3: Install necessary dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install kaggle  # Ensure Kaggle CLI is installed

      # Step 4: Download the dataset from Kaggle
      - name: Download Dataset
        run: |
          kaggle datasets download -d abdelrahman16/co2-emissions-usa -p data  

      # Step 5: Run tests
      - name: Run tests
        run: |
          chmod +x tests.sh
          ./tests.sh
