name: Continuous Integration

on:
  push:
    branches:
      - main
jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install Python and pip
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install kaggle

      # Step 4: Set up Kaggle credentials
      - name: Set up Kaggle credentials
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
          mkdir -p ~/.kaggle
          echo '{"username":"${KAGGLE_USERNAME}","key":"${KAGGLE_KEY}"}' > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      # Step 5: Create data directory if not exists
      - name: Create data directory
        run: mkdir -p data

      # Step 6: Download Dataset 1 (Emissions)
      - name: Download Dataset 1 (Emissions)
        run: kaggle datasets download -d abdelrahman16/co2-emissions-usa -p data

      # Step 7: Download Dataset 2 (Renewable Energy Consumption)
      - name: Download Dataset 2 (Renewable Energy Consumption)
        run: kaggle datasets download -d alistairking/renewable-energy-consumption-in-the-u-s -p data
      # Step 8: Run tests
      - name: Run tests
        run: |
          cd project
          sh tests.sh
