name: Continuous Integration

# Trigger this workflow on every push to the main branch
on:
  push:
    branches:
      - main
    paths:
      - project/**

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Run the test script
      - name: Run Tests
        run: |
          chmod +x tests.sh
        env:
          # Use CI secrets for sensitive information
          SECRET_API_KEY: ${{ secrets.SECRET_API_KEY }}
        
