name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

    

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install kaggle

      # Step 4: Create data directory if not exists
      - name: Create data directory
        run: |
          mkdir -p data

      # Step 5: Download datasets from Kaggle
      - name: Download Dataset 1 (Emissions)
        run: |
          kaggle datasets download -d abdelrahman16/co2-emissions-usa -p data

      # Step 6: Download Dataset 2 (Renewable Energy Consumption)
      - name: Download Dataset 2 (Renewable Energy Consumption)
        run: |
          kaggle datasets download -d alistairking/renewable-energy-consumption-in-the-u-s -p data

      # Step 7: Run tests
      - name: Run tests
        run: |
          chmod +x ./project/tests.sh
          ./project/tests.sh
