name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment and dependencies
      - name: Set up Python environment
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # Step 3: Install Kaggle CLI and configure it
      - name: Install Kaggle CLI
        run: |
          pip install kaggle
          mkdir -p ~/.kaggle
          echo "${{ secrets.KAGGLE_JSON }}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      # Step 4: Download the dataset
      - name: Download dataset
        run: |
          mkdir -p data
          kaggle datasets download -d your-dataset-id -p data/
          unzip data/*.zip -d data/
          ls -la data  # List contents for debugging

      # Step 5: Run the tests
      - name: Run Tests
        run: |
          cd project
          chmod +x tests.sh
          ./tests.sh
        env:
          SECRET_API_KEY: ${{ secrets.SECRET_API_KEY }}
