name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Kaggle API credentials
      - name: Set up Kaggle API credentials
        run: |
          mkdir -p ~/.kaggle
          echo "${{ secrets.KAGGLE_JSON }}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      # Step 3: Debugging: Verify Kaggle API key
      - name: Debugging: Verify Kaggle API key
        run: cat ~/.kaggle/kaggle.json

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install kaggle

      # Step 5: Create data directory if not exists
      - name: Create data directory
        run: |
          mkdir -p data

      # Step 6: Download datasets from Kaggle
      - name: Download Dataset 1 (Emissions)
        run: |
          kaggle datasets download -d abdelrahman16/co2-emissions-usa -p data

      # Step 7: Download Dataset 2 (Renewable Energy Consumption)
      - name: Download Dataset 2 (Renewable Energy Consumption)
        run: |
          kaggle datasets download -d alistairking/renewable-energy-consumption-in-the-u-s -p data

      # Step 8: Run tests
      - name: Run tests
        run: |
          chmod +x tests.sh
          ./tests.sh
