name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Run the test script
      - name: Run Tests
        run: |
          cd project       
          chmod +x tests.sh
          ./tests.sh
        env:
          SECRET_API_KEY: ${{ secrets.SECRET_API_KEY }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
